### ISSUE TITLE
Job Stories

### ISSUE THREAD

**Issue by dandevri** [StefanGerrits2/datingwebsite-bloktech#1]
> Wanneer ik vind dat mijn profiel vernieuwing nodig heeft, wil ik een nieuwe foto kunnen uploaden met een stuk tekst, zodat anderen meer te weten komen over mij.

Most of your Job Stories focus heavily on the account page, I think there are way more features a dating-app should have. If you want to focus on the accountpage I would expand on this Job Story. So uploading a photo is a bit to small. Then I would also incorporate:

> Wanneer ik weinig tijd heb om een bepaald profiel te bekijken die ik leuk vind, wil ik deze op kunnen slaan, zodat ik deze later terug kan vinden wanneer ik wel genoeg tijd heb om het profiel te bekijken.

Apart from uploading a photo, try to think what other features an account page should have that are beyond basic information. 

These are also quite generic, every dating app should have these basic features. In your persona you focus on table tennis, should the user have an club associated to them or their favorite brand of bats?

**Comment by StefanGerrits2** [comment]
I've thought about my job story and I figured I want to focus more on table tennis,
I came up with this job story:

Wanneer ik een partner wil vinden om mee te tafeltennissen, wil ik een club kunnen toevoegen aan mijn profiel waar ik lid van ben, zodat ik andere partners kan vinden die lid zijn van een club die in de buurt zitten.

When you got some time, can you give me some feedback about this job story? Thanks.

**Comment by dandevri** [comment]
The focus group is good, adding clubs to your profile is a niche. But the way your _js_ is currently written it are basically three features.

* Finding people (so a search field etc.)
* Adding clubs (form for input)
* Finding other users (matching, search fields etc.)

What are you going to focus on first?

**Comment by StefanGerrits2** [comment]
I will focus on adding the club first. When I got time I can try to focus on the other features.

I will rewrite my job story:

Wanneer ik lid ben van een club, wil ik deze club kunnen toevoegen aan mijn profiel met bijbehorende data zodat anderen kunnen zien van welke club ik lid ben.
